sudo: required
dist: trusty
language: generic
compiler:
  - gcc
env:
  matrix:
    - ROS_DISTRO="kinetic"
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - .ci_config/travis.sh
